# Generated by Django 4.1.3 on 2022-11-03 22:23

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=apps.core.models.Board.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.board'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=apps.core.models.Task.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='core.task'),
        ),
    ]
