# Generated by Django 4.1.3 on 2022-11-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_column_board_subtask_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='column',
            old_name='order',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='position',
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('column', 'position')},
        ),
    ]
