# Generated by Django 4.1.3 on 2022-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_column_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
